version: '3.8'
services:
  web:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./services/backend/Artisans/.env
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./services/backend/Artisans/db.sqlite3:/app/Artisans/db.sqlite3
    environment:
      - DEBUG=False
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  static_volume:
  media_volume:
