# Generated by Django 4.2.1 on 2023-05-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisansapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='artisan',
            name='experience',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='artisan',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='artisan',
            name='tel',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artisan',
            name='whatsapp',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
