# Generated by Django 4.2.6 on 2026-05-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artisans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
