# Generated by Django 4.2.6 on 2026-05-04 12:09

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(default='')),
                ('experience', models.TextField(default='')),
                ('location', models.CharField(default='', max_length=200)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=20)),
                ('tel', models.CharField(blank=True, default='', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_badge', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('available_days', models.CharField(default='Mon,Tue,Wed,Thu,Fri', max_length=50)),
                ('available_hours_start', models.TimeField(default='08:00')),
                ('available_hours_end', models.TimeField(default='18:00')),
                ('portfolio_images', models.JSONField(blank=True, default=list)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pending_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=250)),
                ('icon', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('bidding', 'Open for Bids'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('emergency', 'Emergency')], default='medium', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('escrow_id', models.CharField(blank=True, max_length=100, null=True)),
                ('escrow_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_escrow_released', models.BooleanField(default=False)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lead_fee_paid', models.BooleanField(default=False)),
                ('lead_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('artisan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_jobs', to='Artisans.artisan')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Artisans.category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('client', 'Client'), ('artisan', 'Artisan')], default='client', max_length=10)),
                ('nin_number', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('bvn_number', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('nin_verified', models.BooleanField(default=False)),
                ('bvn_verified', models.BooleanField(default=False)),
                ('verification_doc', models.FileField(blank=True, null=True, upload_to='verifications/')),
                ('groups', models.ManyToManyField(related_name='artisans_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='artisans_user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('escrow_hold', 'Escrow Hold'), ('escrow_release', 'Escrow Release'), ('commission', 'Commission Deduction'), ('lead_fee', 'Lead Fee'), ('subscription', 'Subscription Payment'), ('verification_fee', 'Verification Fee'), ('payout', 'Artisan Payout')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Artisans.jobrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_disputed', models.BooleanField(default=False)),
                ('dispute_reason', models.TextField(blank=True, null=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='Artisans.artisan')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='Artisans.jobrequest')),
                ('reviewer', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('subscription_tier', models.CharField(choices=[('basic', 'Basic (Free)'), ('pro', 'Pro (₦5,000/mo)'), ('premium', 'Premium (₦15,000/mo)')], default='basic', max_length=20)),
                ('subscription_expires', models.DateField(blank=True, null=True)),
                ('bids_remaining', models.IntegerField(default=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='JobProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('images', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artisans.artisan')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='Artisans.jobrequest')),
            ],
        ),
        migrations.AddField(
            model_name='artisan',
            name='categories',
            field=models.ManyToManyField(to='Artisans.category'),
        ),
        migrations.AddField(
            model_name='artisan',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'artisan'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('estimated_days', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='Artisans.artisan')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='Artisans.jobrequest')),
            ],
            options={
                'unique_together': {('job', 'artisan')},
            },
        ),
    ]
