# Generated by Django 3.2.12 on 2023-11-04 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artisans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='artisan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Artisans.artisan'),
        ),
    ]
