name = "artisans-frontend"
type = "javascript-next"

pages_build_output_dir = ".vercel/output/static"

[env]
  NEXT_PUBLIC_API_URL = "https://artisans-backend.onrender.com/api"
  NEXT_PUBLIC_WS_URL = "https://artisans-backend.onrender.com"

[vars]
  NODE_VERSION = "18"
